/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/subscribe": {
    /** Subscribe an email to receive notifications about new releases of a GitHub repository. The repository is validated via GitHub API. */
    post: operations["subscribe"];
  };
  "/confirm/{token}": {
    /** Confirms a subscription using the token sent in the confirmation email. */
    get: operations["confirmSubscription"];
  };
  "/unsubscribe/{token}": {
    /** Unsubscribes an email from release notifications using the token sent in emails. */
    get: operations["unsubscribe"];
  };
  "/subscriptions": {
    /** Returns all active subscriptions for the given email address. */
    get: operations["getSubscriptions"];
  };
}

export interface definitions {
  Subscription: {
    /** @description Email address */
    email: string;
    /** @description GitHub repository in owner/repo format */
    repo: string;
    /** @description Whether the subscription is confirmed */
    confirmed?: boolean;
    /** @description Last seen release tag for this repository */
    last_seen_tag?: string;
  };
}

export interface operations {
  /** Subscribe an email to receive notifications about new releases of a GitHub repository. The repository is validated via GitHub API. */
  subscribe: {
    parameters: {
      formData: {
        /** Email address to subscribe */
        email: string;
        /** GitHub repository in owner/repo format (e.g., golang/go) */
        repo: string;
      };
    };
    responses: {
      /** Subscription successful. Confirmation email sent. */
      200: unknown;
      /** Invalid input (e.g., invalid repo format) */
      400: unknown;
      /** Repository not found on GitHub */
      404: unknown;
      /** Email already subscribed to this repository */
      409: unknown;
    };
  };
  /** Confirms a subscription using the token sent in the confirmation email. */
  confirmSubscription: {
    parameters: {
      path: {
        /** Confirmation token */
        token: string;
      };
    };
    responses: {
      /** Subscription confirmed successfully */
      200: unknown;
      /** Invalid token */
      400: unknown;
      /** Token not found */
      404: unknown;
    };
  };
  /** Unsubscribes an email from release notifications using the token sent in emails. */
  unsubscribe: {
    parameters: {
      path: {
        /** Unsubscribe token */
        token: string;
      };
    };
    responses: {
      /** Unsubscribed successfully */
      200: unknown;
      /** Invalid token */
      400: unknown;
      /** Token not found */
      404: unknown;
    };
  };
  /** Returns all active subscriptions for the given email address. */
  getSubscriptions: {
    parameters: {
      query: {
        /** Email address to look up subscriptions for */
        email: string;
      };
    };
    responses: {
      /** Successful operation - list of subscriptions returned */
      200: {
        schema: definitions["Subscription"][];
      };
      /** Invalid email */
      400: unknown;
    };
  };
}

export interface external {}
